### PR TITLE
Update ZenFS to stable versions

### PR DESCRIPTION
**Pull request by james-pre**
This PR updates `@zenfs` packages to stable versions (i.e. `^1.0.0`).

### CODE REVIEW

**Comment by yoursunny** [comment]
This was completed long time ago in commit 5b5fa505cd207d75570f5b082e0dd08285a21c76.
Recently the version matcher is changed to `^` but I continue to see frequent breaking changes in ZenFS, so I may go back to exact version matcher again.

**Comment by james-pre** [comment]
@yoursunny,

For 1.0.0+, the public API is stable and should not change. It should be safe to use.

**Comment by yoursunny** [comment]
> For 1.0.0+, the public API is stable and should not change. It should be safe to use.

I need to have custom implementations of `File` and `FileSystem` interfaces.
Most recently, `_setTypeSync` method is deleted from `File` interface in `@zenfs/core@1.3.4`.

**Comment by james-pre** [comment]
> Most recently, `_setTypeSync` method is deleted from `File` interface in `@zenfs/core@1.3.4`

`_setType`/`_setTypeSync` are clearly internal methods not intended for user consumption. The internal APIs (i.e. things marked with `@internal`, or prefixed with `_`) are not subject to semver requirements and should be avoided in most applications.

With that in mind, `File.chmod` and `File.chmodSync` can now be used to change the file's mode, which makes the API easier to use. Note only the file type or permissions can be changed at once, they can't both be changed in the same call.

**Comment by yoursunny** [comment]
> `_setType`/`_setTypeSync` are clearly internal methods not intended for user consumption.

These are `abstract` methods that MUST be implemented.
How could an external library *implement* the `File` interface without using these methods?

**Comment by james-pre** [comment]
Hence why they were removed. They weren't needed as stand-alone methods, and caused some confusion. Additionally, the problem you just pointed out factored into the decision making.

**Pull request closed without merging**
